blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/liborOmis77/TesenaFest26Libor_Radim_David/discussions
    about: Ask a question or start a discussion instead of opening an issue.
